### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by joncorrin** [manoelsmotoso/angular2-social-auth#1]
So essentially this is angular2-social-login but updated for Angular 4?

**Comment by manoelsmotoso** [comment]
no only a update to Angular 4, but too a bug fix.

https://github.com/heresy/angular2-social-login/issues/10

I just did this, because I needed to upload a module in npm, with this bug solved, and the owner of the previous module was slow to correct.

I hope I have helped.

**Comment by joncorrin** [comment]
Way to go. He hasn't responded to any of my bug issues as well. Are you willing to take a crack at one because I haven't been able to use linkedin, its buggy.
